<a href="https://colab.research.google.com/github/theshivamgiri/Mastercard_virtual_intern/blob/main/MAstercard_Intern_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_excel("/content/drive/MyDrive/GreenTrail Store Data.xlsx")
print("Data loaded successfully!")

Data loaded successfully!

In [5]:
df.head()

,Store ID,Location,Store Size,Store Type,Promotion ID,Type of Promotion,Promotion Start Date,Promotion End Date,Weekly Sales During Promotion,Weekly Sales Before Promotion,Weekly Sales After Promotion,Average Daily Visits During Promotion,Average Daily Visits Before Promotion,Average Daily Visits After Promotion
0,1,New York,2000,Urban,101,Discount,2023-06-01,2023-06-14,50000,30000,35000,400,300,350
1,2,Los Angeles,1500,Suburban,102,Buy-One-Get-One,2023-05-15,2023-05-28,45000,35000,30000,450,400,375
2,3,Chicago,1800,Urban,103,Special Event,2023-07-01,2023-07-14,60000,40000,40000,500,350,450
3,4,Houston,1600,Suburban,104,Discount,2023-06-10,2023-06-24,48000,32000,33000,425,310,320
4,5,Phoenix,1700,Urban,105,Buy-One-Get-One,2023-04-20,2023-05-04,53000,34000,36000,475,350,370

In [17]:
df

,Store ID,Location,Store Size,Store Type,Promotion ID,Type of Promotion,Promotion Start Date,Promotion End Date,Weekly Sales During Promotion,Weekly Sales Before Promotion,Weekly Sales After Promotion,Average Daily Visits During Promotion,Average Daily Visits Before Promotion,Average Daily Visits After Promotion
0,1,New York,2000,Urban,101,Discount,2023-06-01,2023-06-14,50000,30000,35000,400,300,350
1,2,Los Angeles,1500,Suburban,102,Buy-One-Get-One,2023-05-15,2023-05-28,45000,35000,30000,450,400,375
2,3,Chicago,1800,Urban,103,Special Event,2023-07-01,2023-07-14,60000,40000,40000,500,350,450
3,4,Houston,1600,Suburban,104,Discount,2023-06-10,2023-06-24,48000,32000,33000,425,310,320
4,5,Phoenix,1700,Urban,105,Buy-One-Get-One,2023-04-20,2023-05-04,53000,34000,36000,475,350,370
5,6,Philadelphia,1800,Urban,106,Special Event,2023-08-05,2023-08-19,49000,31000,41000,480,300,400
6,7,San Antonio,1400,Suburban,107,Discount,2023-07-15,2023-07-29,42000,39000,37000,350,340,360
7,8,San Diego,2000,Urban,108,Buy-One-Get-One,2023-06-22,2023-07-06,56000,43000,39000,530,420,410
8,9,Dallas,1500,Suburban,109,Special Event,2023-05-10,2023-05-24,47000,36000,38000,420,365,380
9,10,San Jose,1750,Urban,110,Discount,2023-04-15,2023-04-29,52000,33000,41000,500,320,390
10,11,Austin,1600,Suburban,111,Buy-One-Get-One,2023-08-01,2023-08-15,45000,37000,34000,410,370,350
11,12,Jacksonville,1450,Urban,112,Special Event,2023-07-20,2023-08-03,51000,38000,42000,470,360,410
12,13,Fort Worth,1550,Suburban,113,Discount,2023-06-18,2023-07-02,43000,35000,36000,400,340,350
13,14,Columbus,1650,Urban,114,Buy-One-Get-One,2023-05-25,2023-06-08,55000,41000,45000,520,400,430
14,15,Charlotte,1750,Suburban,115,Special Event,2023-04-30,2023-05-14,46000,34000,37000,415,335,360
15,16,Detroit,1900,Urban,116,Discount,2023-08-10,2023-08-24,58000,44000,42000,540,430,420
16,17,El Paso,1300,Suburban,117,Buy-One-Get-One,2023-07-12,2023-07-26,44000,42000,40000,390,380,370
17,18,Memphis,1450,Urban,118,Special Event,2023-06-15,2023-06-29,47000,35000,39000,410,330,380
18,19,Baltimore,1500,Suburban,119,Discount,2023-05-05,2023-05-19,49000,37000,36000,420,360,350
19,20,Boston,1650,Urban,120,Buy-One-Get-One,2023-04-10,2023-04-24,54000,40000,41000,510,390,400
20,21,Nashville,1550,Suburban,121,Special Event,2023-08-15,2023-08-29,45000,33000,35000,400,320,330
21,22,Denver,1600,Urban,122,Discount,2023-07-18,2023-08-01,50000,39000,42000,480,370,400
22,23,Louisville,1350,Suburban,123,Buy-One-Get-One,2023-06-20,2023-07-04,48000,36000,37000,410,350,360
23,24,Portland,1400,Urban,124,Special Event,2023-05-15,2023-05-29,52000,41000,43000,470,400,420
24,25,Milwaukee,1500,Suburban,125,Discount,2023-04-20,2023-05-04,47000,35000,38000,400,340,370

In [38]:
# prompt: draw a graph for average percentage increase in sales from before to during promotions . xlabel - distinct(type of promotion), ylabel = overall avg percentage increase in sales

# Group by promotion type and calculate the average percentage increase in sales
promotion_sales = df.groupby('Type of Promotion')['Percentage Increase in Sales'].mean().reset_index()

# Create the plot
plt.figure(figsize=(10, 6))
sns.barplot(x='Promotion Type', y='Percentage Increase in Sales', data=promotion_sales)
plt.xlabel('Distinct Promotion Type')
plt.ylabel('Overall Average Percentage Increase in Sales')
plt.title('Average Percentage Increase in Sales per Promotion Type')
plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better readability
plt.tight_layout()
plt.show()

KeyError: 'Column not found: Percentage Increase in Sales'

In [8]:
urban_stores = df[df['Store Type'] == 'Urban']['Store ID'].count()
suburban_stores = df[df['Store Type'] == 'Suburban']['Store ID'].count()

print(f"Number of urban stores: {urban_stores}")
print(f"Number of suburban stores: {suburban_stores}")

Number of urban stores: 13
Number of suburban stores: 12

In [19]:
promotion_counts = df['Type of Promotion'].value_counts()
promotion_counts

Type of Promotion
Discount           9
Buy-One-Get-One    8
Special Event      8
Name: count, dtype: int64